### ISSUE TITLE
[FIXED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [oyhovd/fig#1]
Dear @oyhovd,
Could you be so kind to generate ```.exe``` for the rest of us who are merely users w/o compiler?

**Comment by oyhovd** [comment]
I can do that. Note that this is made for, compiled in and dependent on Cygwin, i.e. it won't work in a non-Cygwin environment on Windows. 

Fixed in 30a43602f2a0fe2b474623924a85e0fb765cb1e9

**Comment by sergeevabc** [comment]
Thank you for letting me know, @oyhovd. Alas, the requirement to install Cygwin is a huge dependency, which makes hard, for example, to use this app on-the-go from USB stick. Perhaps adding here the exact ```dlls``` of Cygwin package would ease the burden. Workaround is to use another grep: [sift][1], [pt][2] or [ripgrep][3].

[1]: https://github.com/svent/sift/
[2]: https://github.com/monochromegane/the_platinum_searcher/
[3]: https://github.com/BurntSushi/ripgrep/
